version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db
    ports:
      - "8000:8080"
    command: "python app.py"
  db:
    image: postgres:alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: budgetkeeper_api
      POSTGRES_DB: budgetkeeper
    volumes:
      - budget_data:/var/lib/postgresql/data
  initdb:
    build:
      context: .
      dockerfile: Dockerfile.initdb
    environment:
     - DB_HOST=db
    links:
      - db
    depends_on:
      - db
    volumes:
     - .:/usr/src/app
volumes:
  budget_data: {}